name: shopping_mall
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # Utility packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

#---------------------------- LOCAL ASSETS --------------------------------#
assets:
  - assets/images/
  - assets/icons/
  - assets/fonts/
  - assets/videos/

#---------------------------- LOCAL FONTS --------------------------------#
fonts:
  - family: "Poppins"
    fonts:
      - asset: assets/fonts/Poppins-Bold.ttf
        style: normal
        weight: 600

      - asset: assets/fonts/Poppins-Medium.ttf
        style: normal
        weight: 500

      - asset: assets/fonts/Poppins-Regular.ttf
        style: normal
        weight: 400
